// Auto-generated by scripts/highlight-scenarios.ts — do not edit
export const SCENARIO_HIGHLIGHTS_DARK: Record<string, string[]> = {
  "sync-callstack": [
    "<span style=\"color:#81A1C1\">function</span><span style=\"color:#88C0D0\"> greet</span><span style=\"color:#ECEFF4\">(</span><span style=\"color:#D8DEE9\">name</span><span style=\"color:#ECEFF4\">)</span><span style=\"color:#ECEFF4\"> {</span>",
    "<span style=\"color:#81A1C1\">  return</span><span style=\"color:#ECEFF4\"> `</span><span style=\"color:#A3BE8C\">Hello, </span><span style=\"color:#81A1C1\">${</span><span style=\"color:#D8DEE9\">name</span><span style=\"color:#81A1C1\">}</span><span style=\"color:#A3BE8C\">!</span><span style=\"color:#ECEFF4\">`</span><span style=\"color:#81A1C1\">;</span>",
    "<span style=\"color:#ECEFF4\">}</span>",
    "",
    "<span style=\"color:#81A1C1\">function</span><span style=\"color:#88C0D0\"> welcome</span><span style=\"color:#ECEFF4\">()</span><span style=\"color:#ECEFF4\"> {</span>",
    "<span style=\"color:#81A1C1\">  const</span><span style=\"color:#D8DEE9\"> message</span><span style=\"color:#81A1C1\"> =</span><span style=\"color:#88C0D0\"> greet</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#A3BE8C\">world</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#81A1C1\">;</span>",
    "<span style=\"color:#D8DEE9\">  console</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#88C0D0\">log</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#D8DEE9\">message</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#81A1C1\">;</span>",
    "<span style=\"color:#ECEFF4\">}</span>",
    "",
    "<span style=\"color:#88C0D0\">welcome</span><span style=\"color:#D8DEE9FF\">()</span><span style=\"color:#81A1C1\">;</span>"
  ],
  "webapi-settimeout": [
    "<span style=\"color:#D8DEE9\">console</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#88C0D0\">log</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#A3BE8C\">Start</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#81A1C1\">;</span>",
    "",
    "<span style=\"color:#88C0D0\">setTimeout</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">()</span><span style=\"color:#81A1C1\"> =></span><span style=\"color:#ECEFF4\"> {</span>",
    "<span style=\"color:#D8DEE9\">  console</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#88C0D0\">log</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#A3BE8C\">Timer done</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#81A1C1\">;</span>",
    "<span style=\"color:#ECEFF4\">},</span><span style=\"color:#B48EAD\"> 1000</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#81A1C1\">;</span>",
    "",
    "<span style=\"color:#D8DEE9\">console</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#88C0D0\">log</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#A3BE8C\">End</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#81A1C1\">;</span>"
  ],
  "task-queue-ordering": [
    "<span style=\"color:#88C0D0\">setTimeout</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">()</span><span style=\"color:#81A1C1\"> =></span><span style=\"color:#D8DEE9\"> console</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#88C0D0\">log</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#A3BE8C\">A</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#ECEFF4\">,</span><span style=\"color:#B48EAD\"> 0</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#81A1C1\">;</span>",
    "<span style=\"color:#88C0D0\">setTimeout</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">()</span><span style=\"color:#81A1C1\"> =></span><span style=\"color:#D8DEE9\"> console</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#88C0D0\">log</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#A3BE8C\">B</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#ECEFF4\">,</span><span style=\"color:#B48EAD\"> 0</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#81A1C1\">;</span>",
    "<span style=\"color:#D8DEE9\">console</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#88C0D0\">log</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#A3BE8C\">C</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#81A1C1\">;</span>"
  ],
  "microtask-priority": [
    "<span style=\"color:#88C0D0\">setTimeout</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">()</span><span style=\"color:#81A1C1\"> =></span><span style=\"color:#D8DEE9\"> console</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#88C0D0\">log</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#A3BE8C\">Task</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#ECEFF4\">,</span><span style=\"color:#B48EAD\"> 0</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#81A1C1\">;</span>",
    "",
    "<span style=\"color:#88C0D0\">fetch</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#A3BE8C\">/api/starwars</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#D8DEE9FF\">)</span>",
    "<span style=\"color:#ECEFF4\">  .</span><span style=\"color:#88C0D0\">then</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#D8DEE9\">res</span><span style=\"color:#81A1C1\"> =></span><span style=\"color:#D8DEE9\"> res</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#88C0D0\">json</span><span style=\"color:#D8DEE9FF\">())</span>",
    "<span style=\"color:#ECEFF4\">  .</span><span style=\"color:#88C0D0\">then</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#D8DEE9\">data</span><span style=\"color:#81A1C1\"> =></span><span style=\"color:#D8DEE9\"> console</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#88C0D0\">log</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#D8DEE9\">data</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#D8DEE9\">name</span><span style=\"color:#D8DEE9FF\">))</span><span style=\"color:#81A1C1\">;</span>",
    "",
    "<span style=\"color:#D8DEE9\">console</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#88C0D0\">log</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#A3BE8C\">Sync</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#81A1C1\">;</span>"
  ],
  "render-step": [
    "<span style=\"color:#88C0D0\">requestAnimationFrame</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">()</span><span style=\"color:#81A1C1\"> =></span><span style=\"color:#ECEFF4\"> {</span>",
    "<span style=\"color:#D8DEE9\">  document</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#D8DEE9\">body</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#D8DEE9\">style</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#D8DEE9\">background</span><span style=\"color:#81A1C1\"> =</span><span style=\"color:#ECEFF4\"> \"</span><span style=\"color:#A3BE8C\">blue</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#81A1C1\">;</span>",
    "<span style=\"color:#ECEFF4\">}</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#81A1C1\">;</span>",
    "",
    "<span style=\"color:#88C0D0\">setTimeout</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">()</span><span style=\"color:#81A1C1\"> =></span><span style=\"color:#D8DEE9\"> console</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#88C0D0\">log</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#A3BE8C\">Task</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#ECEFF4\">,</span><span style=\"color:#B48EAD\"> 0</span><span style=\"color:#D8DEE9FF\">)</span><span style=\"color:#81A1C1\">;</span>",
    "",
    "<span style=\"color:#88C0D0\">fetch</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#A3BE8C\">/api/starwars</span><span style=\"color:#ECEFF4\">\"</span><span style=\"color:#D8DEE9FF\">)</span>",
    "<span style=\"color:#ECEFF4\">  .</span><span style=\"color:#88C0D0\">then</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#D8DEE9\">res</span><span style=\"color:#81A1C1\"> =></span><span style=\"color:#D8DEE9\"> console</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#88C0D0\">log</span><span style=\"color:#D8DEE9FF\">(</span><span style=\"color:#D8DEE9\">res</span><span style=\"color:#ECEFF4\">.</span><span style=\"color:#88C0D0\">json</span><span style=\"color:#D8DEE9FF\">()))</span><span style=\"color:#81A1C1\">;</span>"
  ]
}

export const SCENARIO_HIGHLIGHTS_LIGHT: Record<string, string[]> = {
  "sync-callstack": [
    "<span style=\"color:#D73A49\">function</span><span style=\"color:#6F42C1\"> greet</span><span style=\"color:#24292E\">(</span><span style=\"color:#E36209\">name</span><span style=\"color:#24292E\">) {</span>",
    "<span style=\"color:#D73A49\">  return</span><span style=\"color:#032F62\"> `Hello, ${</span><span style=\"color:#24292E\">name</span><span style=\"color:#032F62\">}!`</span><span style=\"color:#24292E\">;</span>",
    "<span style=\"color:#24292E\">}</span>",
    "",
    "<span style=\"color:#D73A49\">function</span><span style=\"color:#6F42C1\"> welcome</span><span style=\"color:#24292E\">() {</span>",
    "<span style=\"color:#D73A49\">  const</span><span style=\"color:#005CC5\"> message</span><span style=\"color:#D73A49\"> =</span><span style=\"color:#6F42C1\"> greet</span><span style=\"color:#24292E\">(</span><span style=\"color:#032F62\">\"world\"</span><span style=\"color:#24292E\">);</span>",
    "<span style=\"color:#24292E\">  console.</span><span style=\"color:#6F42C1\">log</span><span style=\"color:#24292E\">(message);</span>",
    "<span style=\"color:#24292E\">}</span>",
    "",
    "<span style=\"color:#6F42C1\">welcome</span><span style=\"color:#24292E\">();</span>"
  ],
  "webapi-settimeout": [
    "<span style=\"color:#24292E\">console.</span><span style=\"color:#6F42C1\">log</span><span style=\"color:#24292E\">(</span><span style=\"color:#032F62\">\"Start\"</span><span style=\"color:#24292E\">);</span>",
    "",
    "<span style=\"color:#6F42C1\">setTimeout</span><span style=\"color:#24292E\">(() </span><span style=\"color:#D73A49\">=></span><span style=\"color:#24292E\"> {</span>",
    "<span style=\"color:#24292E\">  console.</span><span style=\"color:#6F42C1\">log</span><span style=\"color:#24292E\">(</span><span style=\"color:#032F62\">\"Timer done\"</span><span style=\"color:#24292E\">);</span>",
    "<span style=\"color:#24292E\">}, </span><span style=\"color:#005CC5\">1000</span><span style=\"color:#24292E\">);</span>",
    "",
    "<span style=\"color:#24292E\">console.</span><span style=\"color:#6F42C1\">log</span><span style=\"color:#24292E\">(</span><span style=\"color:#032F62\">\"End\"</span><span style=\"color:#24292E\">);</span>"
  ],
  "task-queue-ordering": [
    "<span style=\"color:#6F42C1\">setTimeout</span><span style=\"color:#24292E\">(() </span><span style=\"color:#D73A49\">=></span><span style=\"color:#24292E\"> console.</span><span style=\"color:#6F42C1\">log</span><span style=\"color:#24292E\">(</span><span style=\"color:#032F62\">\"A\"</span><span style=\"color:#24292E\">), </span><span style=\"color:#005CC5\">0</span><span style=\"color:#24292E\">);</span>",
    "<span style=\"color:#6F42C1\">setTimeout</span><span style=\"color:#24292E\">(() </span><span style=\"color:#D73A49\">=></span><span style=\"color:#24292E\"> console.</span><span style=\"color:#6F42C1\">log</span><span style=\"color:#24292E\">(</span><span style=\"color:#032F62\">\"B\"</span><span style=\"color:#24292E\">), </span><span style=\"color:#005CC5\">0</span><span style=\"color:#24292E\">);</span>",
    "<span style=\"color:#24292E\">console.</span><span style=\"color:#6F42C1\">log</span><span style=\"color:#24292E\">(</span><span style=\"color:#032F62\">\"C\"</span><span style=\"color:#24292E\">);</span>"
  ],
  "microtask-priority": [
    "<span style=\"color:#6F42C1\">setTimeout</span><span style=\"color:#24292E\">(() </span><span style=\"color:#D73A49\">=></span><span style=\"color:#24292E\"> console.</span><span style=\"color:#6F42C1\">log</span><span style=\"color:#24292E\">(</span><span style=\"color:#032F62\">\"Task\"</span><span style=\"color:#24292E\">), </span><span style=\"color:#005CC5\">0</span><span style=\"color:#24292E\">);</span>",
    "",
    "<span style=\"color:#6F42C1\">fetch</span><span style=\"color:#24292E\">(</span><span style=\"color:#032F62\">\"/api/starwars\"</span><span style=\"color:#24292E\">)</span>",
    "<span style=\"color:#24292E\">  .</span><span style=\"color:#6F42C1\">then</span><span style=\"color:#24292E\">(</span><span style=\"color:#E36209\">res</span><span style=\"color:#D73A49\"> =></span><span style=\"color:#24292E\"> res.</span><span style=\"color:#6F42C1\">json</span><span style=\"color:#24292E\">())</span>",
    "<span style=\"color:#24292E\">  .</span><span style=\"color:#6F42C1\">then</span><span style=\"color:#24292E\">(</span><span style=\"color:#E36209\">data</span><span style=\"color:#D73A49\"> =></span><span style=\"color:#24292E\"> console.</span><span style=\"color:#6F42C1\">log</span><span style=\"color:#24292E\">(data.name));</span>",
    "",
    "<span style=\"color:#24292E\">console.</span><span style=\"color:#6F42C1\">log</span><span style=\"color:#24292E\">(</span><span style=\"color:#032F62\">\"Sync\"</span><span style=\"color:#24292E\">);</span>"
  ],
  "render-step": [
    "<span style=\"color:#6F42C1\">requestAnimationFrame</span><span style=\"color:#24292E\">(() </span><span style=\"color:#D73A49\">=></span><span style=\"color:#24292E\"> {</span>",
    "<span style=\"color:#24292E\">  document.body.style.background </span><span style=\"color:#D73A49\">=</span><span style=\"color:#032F62\"> \"blue\"</span><span style=\"color:#24292E\">;</span>",
    "<span style=\"color:#24292E\">});</span>",
    "",
    "<span style=\"color:#6F42C1\">setTimeout</span><span style=\"color:#24292E\">(() </span><span style=\"color:#D73A49\">=></span><span style=\"color:#24292E\"> console.</span><span style=\"color:#6F42C1\">log</span><span style=\"color:#24292E\">(</span><span style=\"color:#032F62\">\"Task\"</span><span style=\"color:#24292E\">), </span><span style=\"color:#005CC5\">0</span><span style=\"color:#24292E\">);</span>",
    "",
    "<span style=\"color:#6F42C1\">fetch</span><span style=\"color:#24292E\">(</span><span style=\"color:#032F62\">\"/api/starwars\"</span><span style=\"color:#24292E\">)</span>",
    "<span style=\"color:#24292E\">  .</span><span style=\"color:#6F42C1\">then</span><span style=\"color:#24292E\">(</span><span style=\"color:#E36209\">res</span><span style=\"color:#D73A49\"> =></span><span style=\"color:#24292E\"> console.</span><span style=\"color:#6F42C1\">log</span><span style=\"color:#24292E\">(res.</span><span style=\"color:#6F42C1\">json</span><span style=\"color:#24292E\">()));</span>"
  ]
}
