/**
 * Pre-generates syntax-highlighted HTML for all scenarios at build time.
 * This removes shiki (~400KB) from the client bundle entirely.
 *
 * Run: bun scripts/highlight-scenarios.ts
 */
import { codeToHtml } from 'shiki'

// Import scenario source code directly to avoid pulling in simulation types
const SCENARIO_CODES: Record<string, string> = {
  'sync-callstack': `function greet(name) {
  return \`Hello, \${name}!\`;
}

function welcome() {
  const message = greet("world");
  console.log(message);
}

welcome();`,

  'webapi-settimeout': `console.log("Start");

setTimeout(() => {
  console.log("Timer done");
}, 1000);

console.log("End");`,

  'task-queue-ordering': `setTimeout(() => console.log("A"), 0);
setTimeout(() => console.log("B"), 0);
console.log("C");`,

  'microtask-priority': `setTimeout(() => console.log("Task"), 0);

fetch("/api/starwars")
  .then(res => res.json())
  .then(data => console.log(data.name));

console.log("Sync");`,

  'render-step': `requestAnimationFrame(() => {
  document.body.style.background = "blue";
});

setTimeout(() => console.log("Task"), 0);

fetch("/api/starwars")
  .then(res => console.log(res.json()));`,
}

function extractLines(html: string): string[] {
  const codeMatch = html.match(/<code[^>]*>([\s\S]*)<\/code>/)
  if (!codeMatch) return []
  // Shiki wraps each line in <span class="line">...</span>
  // We need to extract the inner content of each line span.
  const lines = codeMatch[1]
    .split(/<span class="line">/)
    .filter(Boolean)
    .map((l) => {
      // Remove trailing </span> that closes the line span, and any trailing newline
      return l.replace(/<\/span>\s*$/, '').replace(/\n$/, '')
    })
  return lines
}

async function main() {
  const result: Record<string, string[]> = {}

  for (const [id, code] of Object.entries(SCENARIO_CODES)) {
    const html = await codeToHtml(code, { lang: 'javascript', theme: 'nord' })
    result[id] = extractLines(html)
  }

  const output = `// Auto-generated by scripts/highlight-scenarios.ts — do not edit
export const SCENARIO_HIGHLIGHTS: Record<string, string[]> = ${JSON.stringify(result, null, 2)}
`

  const path = new URL('../src/lib/__generated__/scenarioHighlights.ts', import.meta.url).pathname
  await Bun.write(path, output)
  console.log(`Wrote ${Object.keys(result).length} highlighted scenarios to src/lib/__generated__/scenarioHighlights.ts`)
}

main()
