/**
 * Pre-generates syntax-highlighted HTML for all scenarios at build time.
 * This removes shiki (~400KB) from the client bundle entirely.
 *
 * Run: bun scripts/highlight-scenarios.ts
 */
import { codeToHtml } from 'shiki'

// Import scenario source code directly to avoid pulling in simulation types
const SCENARIO_CODES: Record<string, string> = {
	'sync-callstack': `function greet(name) {
  return \`Hello, \${name}!\`;
}

function welcome() {
  const message = greet("world");
  console.log(message);
}

welcome();`,

	'webapi-settimeout': `console.log("Start");

setTimeout(() => {
  console.log("Timer done");
}, 1000);

console.log("End");`,

	'task-queue-ordering': `setTimeout(() => console.log("A"), 1000);
setTimeout(() => console.log("B"), 3000);
console.log("C");`,

	'microtask-priority': `setTimeout(() => console.log("Task"), 2000);

fetch("/api/starwars")
  .then(res => res.json())
  .then(data => console.log(data.name));

console.log("Sync");`,

	'render-step': `requestAnimationFrame(() => document.body.style.background = "red");

setTimeout(() => console.log("Task"), 1000);

fetch("/api/starwars")
  .then(res => res.json())
  .then(data => console.log(data.name));`,
}

function extractLines(html: string): string[] {
	const codeMatch = html.match(/<code[^>]*>([\s\S]*)<\/code>/)
	if (!codeMatch) return []
	// Shiki wraps each line in <span class="line">...</span>
	// We need to extract the inner content of each line span.
	const lines = codeMatch[1]
		.split(/<span class="line">/)
		.filter(Boolean)
		.map((l) => {
			// Remove trailing </span> that closes the line span, and any trailing newline
			return l.replace(/<\/span>\s*$/, '').replace(/\n$/, '')
		})
	return lines
}

// Static (non-interactive) code blocks used in MDX prose
const STATIC_CODES: Record<string, string> = {
	'blocking-while-loop': `// This blocks EVERYTHING for ~3 seconds
while (Date.now() < Date.now() + 3000) {
  // The cursor is stuck. Nothing else can run.
}`,

	'infinite-microtasks': `// if you ever wanted to freeze your browser with microtasks, here's the recipe
function forever() {
  Promise.resolve().then(forever);
}
forever();`,
}

async function main() {
	const dark: Record<string, string[]> = {}
	const light: Record<string, string[]> = {}

	for (const [id, code] of Object.entries(SCENARIO_CODES)) {
		const darkHtml = await codeToHtml(code, {
			lang: 'javascript',
			theme: 'nord',
		})
		dark[id] = extractLines(darkHtml)

		const lightHtml = await codeToHtml(code, {
			lang: 'javascript',
			theme: 'github-light',
		})
		light[id] = extractLines(lightHtml)
	}

	const scenarioOutput = `// Auto-generated by scripts/highlight-scenarios.ts — do not edit
export const SCENARIO_HIGHLIGHTS_DARK: Record<string, string[]> = ${JSON.stringify(dark, null, 2)}

export const SCENARIO_HIGHLIGHTS_LIGHT: Record<string, string[]> = ${JSON.stringify(light, null, 2)}
`

	// Static code blocks
	const staticDark: Record<string, string> = {}
	const staticLight: Record<string, string> = {}

	for (const [id, code] of Object.entries(STATIC_CODES)) {
		staticDark[id] = await codeToHtml(code, {
			lang: 'javascript',
			theme: 'nord',
		})
		staticLight[id] = await codeToHtml(code, {
			lang: 'javascript',
			theme: 'github-light',
		})
	}

	const staticOutput = `// Auto-generated by scripts/highlight-scenarios.ts — do not edit
export const STATIC_HIGHLIGHTS_DARK: Record<string, string> = ${JSON.stringify(staticDark, null, 2)}

export const STATIC_HIGHLIGHTS_LIGHT: Record<string, string> = ${JSON.stringify(staticLight, null, 2)}
`

	const scenarioPath = new URL(
		'../src/lib/__generated__/scenarioHighlights.ts',
		import.meta.url,
	).pathname
	const staticPath = new URL(
		'../src/lib/__generated__/staticHighlights.ts',
		import.meta.url,
	).pathname
	await Bun.write(scenarioPath, scenarioOutput)
	await Bun.write(staticPath, staticOutput)
	console.log(
		`Wrote ${Object.keys(dark).length} highlighted scenarios (dark + light) to src/lib/__generated__/scenarioHighlights.ts`,
	)
	console.log(
		`Wrote ${Object.keys(staticDark).length} static code blocks (dark + light) to src/lib/__generated__/staticHighlights.ts`,
	)
}

main()
